services:
  db:
    image: postgres:15
    env_file: config.env
    ports:
      - "5432:5432"
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      - db_data:/var/lib/postgresql/data

  app:
    build: .
    env_file: config.env
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  db_data: